# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: cicd flow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-workflow:tagname .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-workflow

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Pull Docker Image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 156.67.81.207
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ..
            cd /home/tp1/Yassine_Dlimi
            docker pull ${{ secrets.DOCKER_USERNAME }}/github-workflow
            docker stop container-deeeler || true
            docker rm container-deeeler || true
            docker run -d --name container-deeeler -p 8025:8025 -v /home/tp1/Yassine_Dlimi:/app ${{ secrets.DOCKER_USERNAME }}/github-workflow
