name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build -t dlimiyassin/testcicd .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push dlimiyassin/testcicd
    
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to Server and Pull Docker Image
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 156.67.81.207
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ..
          cd /home/tp1/Yassine_Dlimi
          docker pull ${{ secrets.DOCKER_USERNAME }}/abdelkarimtesttp1
          docker stop container-yassin || true
          docker rm container-yassin || true
          docker run -d --name container-abdel -p 6767:6767 -v /home/tp1/Yassine_Dlimi:/app ${{ secrets.DOCKER_USERNAME }}/testcicd
